### ISSUE TITLE
第一阶段任务列表

### ISSUE THREAD

**Issue by Furffico** [sumsc-caa/pandora-2023-questionnaire#1]
第一阶段的目的是把网站的框架与核心功能（展示问卷，存储问卷结果）搭好。

页面：
- [x] 1. HTML | 提交成功页 | [templates/success.html](/sumsc-caa/pandora-2023-questionnaire/tree/main/templates/success.html)（状态页面设计，3分）#5
- [x] 2. HTML | 错误页 | [templates/errorpage.html](/sumsc-caa/pandora-2023-questionnaire/tree/main/templates/errorpage.html) （状态页面设计，3分）#9
- [x] 3. HTML | 主页 | [templates/index.html](/sumsc-caa/pandora-2023-questionnaire/tree/main/templates/index.html) （页面设计，5分）#10

组件：
- [x] 4. HTML + py | BoxSelect | components/BoxSelect.py（3分）#6 （+1分）
- [x] 5. HTML + py | RadioSelect | components/RadioSelect.py（2分）#9
- [x] 6. HTML + py | DropdownSelect | components/DropdownSelect.py（2分）#12
- [ ] 7. HTML + py | Range | components/Range.py（2~3分*）
- [x] 8. HTML + py | Switch | components/Switch.py（2分）#4
- [ ] 9. HTML + py | Textarea | components/Textarea.py（2~4分*）

负责组件的同学运行程序后可以在 http://127.0.0.1:5000/questionnaire/2 测试自己编写的组件。

服务：
- [x] 10. py + SQL | 主页信息获取 | service/index.py （5分）#7
- [x] 11. py + SQL | 数据存储 | service/submit.py （5分）#8

\* 存在可选的加分项

**Comment by Furffico** [comment]
### 得分榜
目前为人力统计，数据更新存在延迟。

| GitHub id | 正在解决 | 已解决 | 得分 |
| ---- | ---- | ---- | ---- |
| @SuperTeea  | | Q1 Q3 Q8 | 10 |
| @FlowRays  |  | Q2 Q4 Q5 Q6 Q10 Q11 | 21 |

**Comment by SuperTeea** [comment]
认领任务8 ~~来吃个螃蟹~~

**Comment by FlowRays** [comment]
认领任务4

**Comment by SuperTeea** [comment]
认领任务1

**Comment by FlowRays** [comment]
认领任务10

**Comment by SuperTeea** [comment]
认领任务3

**Comment by FlowRays** [comment]
认领任务2

**Comment by FlowRays** [comment]
认领任务5

**Comment by FlowRays** [comment]
认领任务6

**Comment by Furffico** [comment]
比赛结束啦，感谢大家的参与！
